import { WAD } from "@gearbox-protocol/sdk";
import { BigNumber } from "ethers";

import { PoolConfig } from "../core/pool";

export const mainnetPools: Array<PoolConfig> = [
  {
    symbol: "WETH",
    U_optimal: 8000,
    U_reserve: 9000,
    R_base: 0,
    R_slope1: 250,
    R_slope2: 2000,
    R_slope3: 10000,
    expectedLiquidityLimit: WAD.mul(30000),
    supportsQuotas: true,
    quotedTokens: [
      { symbol: "CVX", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "FXS", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "LQTY", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "CRV", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "LDO", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "SNX", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
    ],
  },
  {
    symbol: "wstETH",
    U_optimal: 8000,
    U_reserve: 9000,
    R_base: 0,
    R_slope1: 250,
    R_slope2: 2000,
    R_slope3: 10000,
    expectedLiquidityLimit: WAD.mul(30000),
    supportsQuotas: true,
    quotedTokens: [
      { symbol: "CVX", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "FXS", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "LQTY", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "CRV", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "LDO", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
      { symbol: "SNX", minRate: 10, maxRate: 300, totalLimit: WAD.mul(300) },
    ],
  },
  {
    symbol: "WBTC",
    U_optimal: 8000,
    U_reserve: 9000,
    R_base: 0,
    R_slope1: 250,
    R_slope2: 2000,
    R_slope3: 10000,
    expectedLiquidityLimit: BigNumber.from(10 ** 8).mul(200),
    supportsQuotas: true,
    quotedTokens: [
      {
        symbol: "CVX",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
      {
        symbol: "FXS",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
      {
        symbol: "LQTY",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
      {
        symbol: "CRV",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
      {
        symbol: "LDO",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
      {
        symbol: "SNX",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 8).mul(20),
      },
    ],
  },
  {
    symbol: "DAI",
    U_optimal: 8000,
    U_reserve: 9000,
    R_base: 0,
    R_slope1: 100,
    R_slope2: 1000,
    R_slope3: 10000,
    expectedLiquidityLimit: WAD.mul(50_000_000),
    supportsQuotas: true,
    quotedTokens: [
      {
        symbol: "CVX",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
      {
        symbol: "FXS",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
      {
        symbol: "LQTY",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
      {
        symbol: "CRV",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
      {
        symbol: "LDO",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
      {
        symbol: "SNX",
        minRate: 10,
        maxRate: 300,
        totalLimit: WAD.mul(5_000_000),
      },
    ],
  },
  {
    symbol: "USDC",
    U_optimal: 8000,
    U_reserve: 9000,
    R_base: 0,
    R_slope1: 100,
    R_slope2: 1000,
    R_slope3: 10000,
    expectedLiquidityLimit: BigNumber.from(10 ** 6).mul(50_000_000),
    supportsQuotas: true,
    quotedTokens: [
      {
        symbol: "CVX",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
      {
        symbol: "FXS",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
      {
        symbol: "LQTY",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
      {
        symbol: "CRV",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
      {
        symbol: "LDO",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
      {
        symbol: "SNX",
        minRate: 10,
        maxRate: 300,
        totalLimit: BigNumber.from(10 ** 6).mul(5_000_000),
      },
    ],
  },
];
