/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISupportedContracts__factory } from "./ISupportedContracts__factory";
export { SupportedContracts__factory } from "./SupportedContracts__factory";
