/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface UniswapV2AdapterInterface extends utils.Interface {
  functions: {
    "_acl()": FunctionFragment;
    "_gearboxAdapterType()": FunctionFragment;
    "_gearboxAdapterVersion()": FunctionFragment;
    "addressProvider()": FunctionFragment;
    "connectorToken0()": FunctionFragment;
    "connectorToken1()": FunctionFragment;
    "connectorToken2()": FunctionFragment;
    "connectorToken3()": FunctionFragment;
    "connectorToken4()": FunctionFragment;
    "connectorToken5()": FunctionFragment;
    "connectorToken6()": FunctionFragment;
    "connectorToken7()": FunctionFragment;
    "connectorToken8()": FunctionFragment;
    "connectorToken9()": FunctionFragment;
    "creditManager()": FunctionFragment;
    "getConnectors()": FunctionFragment;
    "isConnector(address)": FunctionFragment;
    "numConnectors()": FunctionFragment;
    "swapAllTokensForTokens(uint256,address[],uint256)": FunctionFragment;
    "swapExactTokensForTokens(uint256,uint256,address[],address,uint256)": FunctionFragment;
    "swapTokensForExactTokens(uint256,uint256,address[],address,uint256)": FunctionFragment;
    "targetContract()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_acl"
      | "_gearboxAdapterType"
      | "_gearboxAdapterVersion"
      | "addressProvider"
      | "connectorToken0"
      | "connectorToken1"
      | "connectorToken2"
      | "connectorToken3"
      | "connectorToken4"
      | "connectorToken5"
      | "connectorToken6"
      | "connectorToken7"
      | "connectorToken8"
      | "connectorToken9"
      | "creditManager"
      | "getConnectors"
      | "isConnector"
      | "numConnectors"
      | "swapAllTokensForTokens"
      | "swapExactTokensForTokens"
      | "swapTokensForExactTokens"
      | "targetContract"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "_acl", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_gearboxAdapterType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_gearboxAdapterVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addressProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken6",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken7",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken8",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "connectorToken9",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConnectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isConnector",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "numConnectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapAllTokensForTokens",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactTokens",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "targetContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "_acl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_gearboxAdapterType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_gearboxAdapterVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken7",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "connectorToken9",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConnectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConnector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numConnectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAllTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetContract",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UniswapV2Adapter extends BaseContract {
  contractName: "UniswapV2Adapter";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapV2AdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _acl(overrides?: CallOverrides): Promise<[string]>;

    _gearboxAdapterType(overrides?: CallOverrides): Promise<[number]>;

    _gearboxAdapterVersion(overrides?: CallOverrides): Promise<[number]>;

    addressProvider(overrides?: CallOverrides): Promise<[string]>;

    connectorToken0(overrides?: CallOverrides): Promise<[string]>;

    connectorToken1(overrides?: CallOverrides): Promise<[string]>;

    connectorToken2(overrides?: CallOverrides): Promise<[string]>;

    connectorToken3(overrides?: CallOverrides): Promise<[string]>;

    connectorToken4(overrides?: CallOverrides): Promise<[string]>;

    connectorToken5(overrides?: CallOverrides): Promise<[string]>;

    connectorToken6(overrides?: CallOverrides): Promise<[string]>;

    connectorToken7(overrides?: CallOverrides): Promise<[string]>;

    connectorToken8(overrides?: CallOverrides): Promise<[string]>;

    connectorToken9(overrides?: CallOverrides): Promise<[string]>;

    creditManager(overrides?: CallOverrides): Promise<[string]>;

    getConnectors(
      overrides?: CallOverrides
    ): Promise<[string[]] & { connectors: string[] }>;

    isConnector(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    numConnectors(overrides?: CallOverrides): Promise<[BigNumber]>;

    swapAllTokensForTokens(
      rateMinRAY: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExactTokensForTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMin: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapTokensForExactTokens(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMax: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    targetContract(overrides?: CallOverrides): Promise<[string]>;
  };

  _acl(overrides?: CallOverrides): Promise<string>;

  _gearboxAdapterType(overrides?: CallOverrides): Promise<number>;

  _gearboxAdapterVersion(overrides?: CallOverrides): Promise<number>;

  addressProvider(overrides?: CallOverrides): Promise<string>;

  connectorToken0(overrides?: CallOverrides): Promise<string>;

  connectorToken1(overrides?: CallOverrides): Promise<string>;

  connectorToken2(overrides?: CallOverrides): Promise<string>;

  connectorToken3(overrides?: CallOverrides): Promise<string>;

  connectorToken4(overrides?: CallOverrides): Promise<string>;

  connectorToken5(overrides?: CallOverrides): Promise<string>;

  connectorToken6(overrides?: CallOverrides): Promise<string>;

  connectorToken7(overrides?: CallOverrides): Promise<string>;

  connectorToken8(overrides?: CallOverrides): Promise<string>;

  connectorToken9(overrides?: CallOverrides): Promise<string>;

  creditManager(overrides?: CallOverrides): Promise<string>;

  getConnectors(overrides?: CallOverrides): Promise<string[]>;

  isConnector(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numConnectors(overrides?: CallOverrides): Promise<BigNumber>;

  swapAllTokensForTokens(
    rateMinRAY: PromiseOrValue<BigNumberish>,
    path: PromiseOrValue<string>[],
    deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExactTokensForTokens(
    amountIn: PromiseOrValue<BigNumberish>,
    amountOutMin: PromiseOrValue<BigNumberish>,
    path: PromiseOrValue<string>[],
    arg3: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapTokensForExactTokens(
    amountOut: PromiseOrValue<BigNumberish>,
    amountInMax: PromiseOrValue<BigNumberish>,
    path: PromiseOrValue<string>[],
    arg3: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  targetContract(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _acl(overrides?: CallOverrides): Promise<string>;

    _gearboxAdapterType(overrides?: CallOverrides): Promise<number>;

    _gearboxAdapterVersion(overrides?: CallOverrides): Promise<number>;

    addressProvider(overrides?: CallOverrides): Promise<string>;

    connectorToken0(overrides?: CallOverrides): Promise<string>;

    connectorToken1(overrides?: CallOverrides): Promise<string>;

    connectorToken2(overrides?: CallOverrides): Promise<string>;

    connectorToken3(overrides?: CallOverrides): Promise<string>;

    connectorToken4(overrides?: CallOverrides): Promise<string>;

    connectorToken5(overrides?: CallOverrides): Promise<string>;

    connectorToken6(overrides?: CallOverrides): Promise<string>;

    connectorToken7(overrides?: CallOverrides): Promise<string>;

    connectorToken8(overrides?: CallOverrides): Promise<string>;

    connectorToken9(overrides?: CallOverrides): Promise<string>;

    creditManager(overrides?: CallOverrides): Promise<string>;

    getConnectors(overrides?: CallOverrides): Promise<string[]>;

    isConnector(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numConnectors(overrides?: CallOverrides): Promise<BigNumber>;

    swapAllTokensForTokens(
      rateMinRAY: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    swapExactTokensForTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMin: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    swapTokensForExactTokens(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMax: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    targetContract(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _acl(overrides?: CallOverrides): Promise<BigNumber>;

    _gearboxAdapterType(overrides?: CallOverrides): Promise<BigNumber>;

    _gearboxAdapterVersion(overrides?: CallOverrides): Promise<BigNumber>;

    addressProvider(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken0(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken1(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken2(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken3(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken4(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken5(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken6(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken7(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken8(overrides?: CallOverrides): Promise<BigNumber>;

    connectorToken9(overrides?: CallOverrides): Promise<BigNumber>;

    creditManager(overrides?: CallOverrides): Promise<BigNumber>;

    getConnectors(overrides?: CallOverrides): Promise<BigNumber>;

    isConnector(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numConnectors(overrides?: CallOverrides): Promise<BigNumber>;

    swapAllTokensForTokens(
      rateMinRAY: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExactTokensForTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMin: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapTokensForExactTokens(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMax: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    targetContract(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _acl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _gearboxAdapterType(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _gearboxAdapterVersion(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addressProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken4(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken5(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken6(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken7(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken8(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    connectorToken9(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creditManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getConnectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isConnector(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numConnectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapAllTokensForTokens(
      rateMinRAY: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTokensForTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMin: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForExactTokens(
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMax: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<string>[],
      arg3: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    targetContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
